### ISSUE TITLE
About Scape Dataset Ground-truth

### ISSUE THREAD

**Issue by cainiaoshidai** [pvnieo/GeomFmaps_pytorch#2]
Hello,
    Thanks, I have got my matches on Scape dataset and now I want to calculate the geodetic error, but I don't know how to use the file of [.vts]. Just like you write in the Readme, the file of .vts is the ground truth maps, but I don't know how to get maps around any pairs shapes, just like the map mesh060.off to mesh061 et al. Looking forward to your reply, thanks. 

Best.

**Comment by pvnieo** [comment]
Hi,
The `.vts` files are ground truth map to a template mesh, so `shape_1.vts` is the p2p from the template to shape_1.
Given a shape_1 and shape_2, and a predicted p2p map from shape_2 to shape_1 `T21`, the geodesic error is:
```
mean_geod_error = geodesic_matrix_shape1[T21[vts_shape2], vts_shape1].mean()
```

**Comment by pvnieo** [comment]
closing the issue, feel free to re-open it if you have further questions!
