### ISSUE TITLE
versions of pip packages in requirement.txt

### ISSUE THREAD

**Issue by pieris98** [pvnieo/GeomFmaps_pytorch#6]
Hey Souhaib,
I'm trying to get the environment to work without much progress.
In the README.md you mention you used python >=3.7, but knowing what version of python and what version of the packages in `requirement.txt` you used when writing the project is important as outdated code and/or package version conflicts make the project _non-reproducible_.

If you have any of the information available and could share, that would be very helpful!

Thanks again for everything you've done.

**Comment by pieris98** [comment]
EDIT: I **still** haven't fixed the issue and cannot run `train.py`.
I followed the last commit date and guessed some versions. I've tried the following so far:
- Used python 3.7.9 `conda create -n geomfmaps python==3.7.9`
- Installed pytorch 1.6.0 with CUDA 10.2 from [here](https://pytorch.org/get-started/previous-versions/#osx-34): `conda install pytorch==1.6.0 torchvision==0.7.0 -c pytorch` (or alternatively `conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2 -c pytorch`)

- Install compatible `torch_scatter` version with CUDA 10.2 (linux): `pip install https://data.pyg.org/whl/torch-1.6.0/torch_scatter-2.0.5%2Bcu102-cp37-cp37m-linux_x86_64.whl`
- Install compatible `torch_cluster` version with CUDA 10.2 (linux): ``
- Install torch_sparse as per [issue](https://github.com/rusty1s/pytorch_sparse/issues/120): 
`pip install https://data.pyg.org/whl/torch-1.6.0/torch_sparse-0.6.7%2Bcu102-cp37-cp37m-linux_x86_64.whl` 

- Install _new_ `requirement.txt` packages. NOTE: Replaced versions with the following in `requirement.txt`:

> `omegaconf`
> `#torch-points3d==1.1.1 #TODO, build from source torch_points_kernels with CUDA 10.2 (no supported packages/wheels in either pip or conda, they only have some for pytorch>=1.10)`
> `tqdm`
> `scipy==1.5.2`
> `numpy==1.17.3 #torch-sparse 0.6.7 only works with this`

If you have _any_ information on the **versions** you used for `python`, `pytorch`, `torch_sparse` and `torch-points3d` - I saw you had been involved in [this GitHub issue](https://github.com/torch-points3d/torch-points-kernels/issues/39) too, your help would be greatly appreciated! 
Also, based on this issue, I would like to ask if you used a `conda` environment or installed on your host machine using `pip`, as this seems to affect where the shared libraries/CUDA/torch-points3d get installed.
Thanks again!

**Comment by pvnieo** [comment]
Dear @pieris98 

Thank you for your interest in our work.

Just so you know, this project is no longer maintained, and I suggest you try the DiffusionNet code base as it's well-documented and generally yields better performance!

Concerning the other projects (VADER, CLOVER, etc), I was very busy in the last couple of months (still busy with the thesis manuscript), I'll try to open source the code as soon as possible, and ping you when they are ready!

Thank you for your patience and interest!

Best,
